# Generated by Django 4.2.6 on 2024-04-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_articulo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default='fotos/no-disponible.jpg', upload_to='fotos'),
        ),
    ]
